### ISSUE TITLE
run error in demo_vlsm.ipynb

### ISSUE THREAD

**Issue by amiltonwong** [akar43/lsm#1]
Hi, @akar43 ,

When I run the following cell in `demo_vlsm.ipynb`, 
```
# Setup TF graph and initialize VLSM model
tf.reset_default_graph()

# Change the ims_per_model to run on different number of views
bs, ims_per_model = 1, 4

ckpt = 'mvnet-100000'
net = MVNet(vmin=-0.5, vmax=0.5, vox_bs=bs,
          im_bs=ims_per_model, grid_size=args.nvox,
          im_h=args.im_h, im_w=args.im_w,
          norm=args.norm, mode="TEST")

net = model_vlsm(net, im_nets[args.im_net], grid_nets[args.grid_net],
                     conv_rnns[args.rnn])
vars_restore = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope='MVNet')
sess = tf.InteractiveSession(config=get_session_config())
saver = tf.train.Saver(var_list=vars_restore)
saver.restore(sess, os.path.join(log_dir, ckpt))
```

I got the this running error ([details log](https://gist.githubusercontent.com/amiltonwong/0d8560992367b03aa04e28f9d10a4b38/raw/6c4cb4c002f5b9a193b23411b1dd80e5792366fd/error%2520log)):

```
ValueError: Dimension must be 6 but is 3 for 'MVNet/transpose' (op: 'Transpose') with input shapes: [1,4,32,32,32,33], [3].
```

Any suggestion to fix this issue?

My system is Tensorflow 1.0.1 (python 2.7). Is the tensorflow version compatibility issue? What version of tensorflow is required to run your package?

Thanks!

**Comment by akar43** [comment]
Hi @amiltonwong ,
Thanks for your interest in our code. This is indeed a tensorflow issue which I believe was fixed in 1.1 or 1.2. You can find the issue [here](https://github.com/tensorflow/tensorflow/issues/8343) and [here](https://stackoverflow.com/questions/42513613/tensorflow-dynamic-rnn-regressor-valueerror-dimension-mismatch). The issue was that TF did not support >3D tensors within `dynamic_rnn` making ConvLSTMs or ConvGRUs impossible to implement using that. They have fixed it after that. Hope this helps.
